apiVersion: v1
kind: Service
metadata:
  name: frontjichi-service
  namespace: "#{{Namespace}}#"
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: frontjichi-deployment
    app.kubernetes.io/component: frontjichi
    app.kubernetes.io/part-of: "#{{Namespace}}#"
  ports:
  - targetPort: 8080
    #puerto de la imagen
    port: 8080
    #puerto de servicio
    nodePort: #{{NodePortFrontJichi}}#